name: appgastos
description: "Registro rápido de gastos con acceso desde el panel de ajustes rápidos de Android."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
